Repository Linc-tw/COVID_breakdown, pull requests merged in 2020-05, with the labels that each got.

#7 Feature/lang cookie
  COVID_breakdown_data_processing.py
  css/plots.css
  index.html
  js/age_symptom_correlations.js
  js/case_by_detection.js
  js/case_by_transmission.js
  js/difference_by_transmission.js
  js/test_by_criterion.js
  js/text_translation.js
  js/travel_history_symptom_correlations.js
  processed_data/age_symptom_counts.csv
  processed_data/case_by_detection_by_onset_day.csv
  processed_data/case_by_detection_by_report_day.csv
  processed_data/case_by_transmission_by_onset_day.csv
  processed_data/case_by_transmission_by_report_day.csv
  processed_data/key_numbers.csv
  processed_data/travel_history_symptom_counts.csv
Labels: enhancement

#13 some French translations in the 'Chronology of Systematic Testing' figure
  COVID_breakdown_data_processing.py
  js/criteria_timeline.js
  js/text_translation.js
Labels: text

#15 Disable google analysis in local
  index.html
Labels: improvement
